// Curated island facts (data/claude-facts.json) — 100 dated, geolocated
// places, events, institutions and people, generated by a frontier model
// from world knowledge and reviewed by hand. Coordinates are approximate;
// text carries a provenance note so readers know what they're getting.

import { readFileSync } from 'node:fs';
import { insideBbox } from '../gazetteer.js';

// lore entries carry their own taxonomy; map it onto the eight display bins
const LORE_CATEGORY = {
  indigenous_heritage: 'culture', naming_lore: 'culture', local_lore: 'culture',
  insider_tip: 'community', marine_hazard: 'marine', natural_history: 'wildlife',
  exploration: 'reference', history: 'reference', research_gap: 'reference',
  wildlife_spot: 'wildlife',
  mystery: 'culture', famous_visitors: 'culture', cryptid_lore: 'culture',
  legend: 'culture', oral_tradition: 'culture', people: 'culture',
  deep_time: 'reference', regional_history: 'reference', sources: 'reference',
};

function categorize(f) {
  if (f.category && LORE_CATEGORY[f.category]) return LORE_CATEGORY[f.category];
  const t = `${f.name} ${f.description}`.toLowerCase();
  if (/whale|wolves|wolf|seabird|bird|salmon|clam garden|old-growth|bioluminescence|wetland/.test(t)) return 'wildlife';
  if (/market|cortes day|festival|annual/.test(f.date) || /market|celebration/.test(t)) return 'event';
  if (/ferry|steamship|channel|anchorage|marina|passage|spit|aquaculture|mv |boat/.test(t)) return 'marine';
  if (/klahoose|tla'amin|homalco|museum|hall|church|radio|writer|novelist|author|school|academy|library|retreat|artist|midden|territory|folk u/.test(t)) return 'culture';
  return 'reference';
}

function importance(f) {
  if (f.category === 'indigenous_heritage') return 0.68;
  if (f.category === 'marine_hazard') return 0.5;
  const t = `${f.name} ${f.description}`.toLowerCase();
  if (/klahoose|territory|midden|clam garden/.test(t)) return 0.7;
  if (/park|museum|hall|co-op|school/.test(t)) return 0.5;
  return 0.38;
}

const FILES = [
  { file: '../../data/claude-facts.json' },
  { file: '../../data/claude-lore.json' },
  { file: '../../data/spots.json' },
  // the esoterica's best stories live in the wider storyshed (Toba, Quadra,
  // Church House) — let them through a bigger box
  { file: '../../data/claude-esoterica.json', wide: true },
];
const WIDE = { south: 49.9, west: -125.35, north: 50.46, east: -124.34 };
const inWide = (lat, lon) => lat >= WIDE.south && lat <= WIDE.north && lon >= WIDE.west && lon <= WIDE.east;

export default {
  name: 'facts',
  async fetch() {
    const out = [];
    for (const { file, wide } of FILES) {
      const data = JSON.parse(readFileSync(new URL(file, import.meta.url), 'utf8'));
      for (const f of data.items) {
        if (!(wide ? inWide(f.latitude, f.longitude) : insideBbox(f.latitude, f.longitude))) continue;
        const conf = f.confidence && f.confidence !== 'documented'
          ? ` [${f.confidence.replace(/_/g, ' ')}]` : '';
        const when = f.date && !/^(n\/a|ongoing)/.test(f.date)
          ? ` (${/^(annual|pre-contact|circa)/.test(f.date) ? f.date : `since ${f.date}`})` : '';
        out.push({
          adapter: 'facts',
          // hazards, tips and habitat knowledge live on the ground; stories float
          tier: ['marine_hazard', 'insider_tip', 'natural_history', 'wildlife_spot'].includes(f.category)
            ? 'ground' : 'float',
          title: f.name,
          link: `https://www.google.com/search?q=${encodeURIComponent(`"${f.name}" Cortes Island BC`)}`,
          summary: `${f.description}${when}${conf}`,
          image: null,
          author: 'island almanac',
          publishedAt: null,
          lat: f.latitude, lon: f.longitude,
          place: f.name,
          category: categorize(f),
          importance: importance(f),
          topics: [f.date, f.category?.replace(/_/g, ' ')].filter(Boolean),
        });
      }
    }
    return out;
  },
};
